### ISSUE TITLE
Add support for php 5.3

### ISSUE THREAD

**Issue by SirPole** [SirPole/dev#16]

**Comment by LukasFranc** [comment]
Jak to vidíš výhledově ?

**Comment by SirPole** [comment]
To bude na dýl... :/ oficiální php repo 5.3 vůbec nepodporuje... https://github.com/docker-library/php/tree/master

Asi to zbuildím ze zdrojů, bylo by to jen kombo apache + php... Budu to muset zbuildit ze zdrojů + hledat kompatibilní pluginy :(

**Comment by LukasFranc** [comment]
Chápu :( ...Nejhorší je, že já s těmahle hujdama starýma pracuju dost často. Jediný řešení by bylo jet na ostrým, ale pokud by to bylo něco většího, tak bych se bál.
