### ISSUE TITLE
.ant permissions and ownership

### ISSUE THREAD

**Issue by SirPole** [SirPole/dev#2]
Couldn't log in to mysql without 755 on whole dir

**Comment by SirPole** [comment]
Probably just once in a lifetime issue (FT)

**Comment by Kammi638** [comment]
Mby create troubleshooting page in wiki? We can describe these problems and workarounds for them.

**Comment by SirPole** [comment]
https://github.com/SirPole/ant-dev/wiki/4.-Troubleshooting

Text should be editable :)
